// Generated by uniffi-bindgen-react-native
#ifdef __cplusplus
#import "react-native-nostr-sdk.h"
#endif

#ifdef RCT_NEW_ARCH_ENABLED
#import "RNNostrSdkSpec.h"

@interface NostrSdk : NSObject <NativeNostrSdkSpec>
#else
#import <React/RCTBridgeModule.h>

@interface NostrSdk : NSObject <RCTBridgeModule>
#endif

@end